# This is a basic workflow to help you get started with Actions

name: CI Job

# Controls when the action will run. 
on:
  # Triggers the workflow on pull to develop branch
  push:
    branches: [ main ]    
  pull_request:
    branches: [ develop, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run mulitple commands for installing salesforce CLI
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install
      
      # Store secret for dev hub
      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

      # Authenticate dev hub
      - name: 'Authenticate Dev Hub'
        run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'

      # Create scratch org
      - name: 'Create scratch org'
        run: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1'

      # Deploy source to scratch org
      - name: 'Push source to scratch org'
        run: 'sfdx force:source:push'
     
      # Run Apex tests in scratch org
      - name: 'Run Apex tests'
        run: 'sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20'
        
      - name: 'Delete scratch org'
        if: always()
        run: 'sfdx force:org:delete -p -u scratch-org' 
      
      - name: 'Deploy to developer sandbox'
        run: 'sfdx force:source:deploy -p force/main/default/ -u devhub'

        
        
        
        
        
        
        
        
        
        
